services:
  - type: web
    name: helixion-backend
    plan: starter
    runtime: python
    repo: https://github.com/pateli18/clinicontact
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.server:app --host 0.0.0.0 --port 8000"
    rootDir: backend
    buildFilter:
      paths:
        - backend/**
    healthCheckPath: /healthz
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
  - type: web
    name: helixion-frontend
    runtime: static
    repo: https://github.com/pateli18/clinicontact
    rootDir: frontend
    buildCommand: npm ci --no-audit; npm run build
    buildFilter:
      paths:
        - frontend/**
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BUILD
        value: "true"
      - key: VITE_ENV
        value: "prod"
      - key: VITE_SENTRY_DSN
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
    headers:
      - path: "/*"
        name: "Strict-Transport-Security"
        value: "max-age=2592000; includeSubDomains"
      - path: "/*"
        name: "X-Frame-Options"
        value: "SAMEORIGIN"
      - path: "/*"
        name: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"
      - path: "/*"
        name: "Permissions-Policy"
        value: "fullscreen=*, microphone=self"
      - path: "/*"
        name: "Content-Security-Policy"
        value: "default-src 'self'; connect-src 'self' blob: wss://*.helixion.ai https://*.helixion.ai *.sentry.io api.openai.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; worker-src 'self' blob:; media-src 'self' data: blob: *.helixion.ai; img-src * data: blob:; font-src 'self' https://fonts.gstatic.com;"